[package]
name = "rust-workshop"
version = "0.2.0"
authors = ["Arild Nilsen", "Eirik Bertelsen", "Marius Nilsen Kluften", "Frederik Rønnevig"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
